### ISSUE TITLE
What version of the game were you targetting?

### ISSUE THREAD

**Issue by yunginnanet** [jtieri/habbgo#11]
Specific revision? r14?

Also, as I go through this on my fork and get to understand where you were going with it, I'll see if I can give back by helping you with some of your issues on a clean branch of your original repo.

**Comment by jtieri** [comment]
I was using v14 as a baseline for starting development with the plan being that logic will be in place to support all versions of the Shockwave client. 

I have been adjusting to a new job + dealing with the holidays but plan to shift some of my focus here as time permits on the weekends. This project was started when I was still in college and learning Go so I plan to overhaul most of what is here before moving forward with implementing the core game logic.

**Comment by yunginnanet** [comment]
> I have been adjusting to a new job + dealing with the holidays

**Same.**

Same. I'm an old school habbo/msn kid from back in the day. Super stoked at what you're doing here. My fork is already pretty deviated, but if I can find the time I will try to give back by helping you out with bugs and whatnot on yours.
